### ISSUE TITLE
Refacto

### ISSUE THREAD

**Issue by nicolashacala** [notREKASH/projet_8_Benmehal_Joris#2]
https://github.com/notREKASH/projet_8_Benmehal_Joris/blob/368a007cdf08e1d2bb5656c789c4f7cfaa9b920f/src/components/carousel/carousel.jsx#L29-L60

On aurait pu simplifier avec:
```javascript
images.length > 1 && (
```

**Comment by notREKASH** [comment]
Simplify ok
